API-5161 - Hidden page to Publish APIs to API Catalogue
hmrc/api-gatekeeper-frontend pull request #373
Opened 2021-10-18 14:19 UTC by anjumabbas5

2021-10-18 14:58 UTC, peteslater-ee commented on app/connectors/ApiCataloguePublishConnector.scala
> +    handleResult(http.POSTEmpty[PublishAllResponse](s"${appConfig.serviceBaseUrl}/api-platform-api-catalogue-publish/publish-all", Seq.empty))
POSTEmpty has a version that doesn't take headers so you don't need the Seq.empty

2021-10-18 15:02 UTC, AndySpaven requested changes

2021-10-18 15:02 UTC, AndySpaven commented on app/controllers/ApiCataloguePublishController.scala
> +    connector.publishAll()
You could use EitherT and fold rather than map and match.

2021-10-18 15:02 UTC, AndySpaven commented on app/model/Model.scala
> +object ApiCataloguePublishResponse {
Ditto

2021-10-19 06:55 UTC, mattclark-zerogravit commented on conf/app.routes
> +# api catalogue publish routes
will do

2021-10-19 06:55 UTC, mattclark-zerogravit commented on app/connectors/ApiCataloguePublishConnector.scala
> +    handleResult(http.POST[String, PublishResponse](s"${appConfig.serviceBaseUrl}/api-platform-api-catalogue-publish/publish/$serviceName", ""))
yeah will chnge

2021-10-19 06:56 UTC, mattclark-zerogravit commented on app/model/Model.scala
> +object ApiCataloguePublishResponse {
:+1:

2021-10-19 11:45 UTC, peteslater-ee approved these changes

2021-10-19 13:58 UTC, merged